### ISSUE TITLE
Windows build failure

### ISSUE THREAD

**Issue by Telsenome** [dustin/gopro#21]
Hi, sorry for this newbie question but I'm not so acquainted with the terminal and this kind of setup. Are there any simple steps I could take to solve these dependence errors?

![image](https://user-images.githubusercontent.com/39857933/222482213-f325ae55-0baf-41ea-9a94-e48e78948235.png)

**Comment by dustin** [comment]
Hmm...  I'm not quite sure how to get those errors.  stack should take care of that.  How did you get stack?

I generally use nix, though it does look like my shell.nix is insufficient.

**Comment by Telsenome** [comment]
@dustin Thank you for taking the time to answer. I just went to https://docs.haskellstack.org/en/stable/install_and_upgrade/ and downloaded the Windows installer to install it. then I followed the instructions from the [readme](https://github.com/dustin/gopro#installation)

**Comment by Telsenome** [comment]
I will try restarting the computer and see what it gives :-)

**Comment by dustin** [comment]
Ah, OK.  I have no exposure to Windows at all.  The dependency failures seem to be around the `unix` package, so it might just be that that's not available.

The `unix` package itself is used for moving files around, path manipulation, and hard linking.  It might be possible to abstract this, but I'd be wildly guessing with no ability to test.

`qsem` and `postgresql-libpq` are possibly easier to work around since they're just complaining about newer libraries being available than they were expecting.

**Comment by Telsenome** [comment]
Will check if anything's wrong with the `unix ` package or if it's not even installed. Thank you for all the help!

**Comment by Telsenome** [comment]
Hi again @dustin, do you know how to install the `unix` package on Windows? I Googled but I'm not sure how to interpret the search results...
