### ISSUE TITLE
Consider the possibility of downloading only originals

### ISSUE THREAD

**Issue by michis0806** [dustin/gopro#4]
Hi,

I'm using your fabulous program to create a local backup from my gopro+ data on a Synology NAS. Everything works perfects so far. But as the program downloads every version of the GoPro+ content, the downloaded data is quite large. 

I'd prefer to only download the original files, ignoring the proxy files or thumbnails. Is this thinkable?

Thanks for your work!
Michael

**Comment by dustin** [comment]
That's an interesting idea.  I wanted to capture all of the data available because some of the derivatives were quite useful, but I also ran out of space.  :)

I think it's only slightly tricky as I think some types of media have different ways to fetch originals, but I've not looked at that in a while.  It's easy enough for me to do some offline analysis on that and confirm.

I think the one case that was particularly interesting to me was time lapse images represented as video, but I should be able to do something somewhat sensible here.

Thanks for the good idea.
